---
# tasks file for bastion
- name: BASTION SERVER | COPY iptables_restore.sh
  copy:
    src: files/iptables_restore.sh
    dest: /root
    
- name: BASTION SERVER | COPY IPTABLES FILE
  copy:
    src: files/iptables-save
    dest: /etc/
    
- name: BASTION SERVER | COPY MYIPTABLES-RESTORE UNIT
  copy:
    src: files/myiptables-restore.service
    dest: /etc/systemd/system/  
    
- name: BASTION SERVER | SET ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
          
- name: BASTION SERVER | ENABLE ip_forward
  lineinfile:
    dest: /etc/sysctl.conf
    line: net.ipv4.ip_forward = 1    
    
- name: BASTION SERVER | DAEMON RELOAD
  systemd:
    daemon-reload: yes 
        
- name: BASTION SERVER | ENABLE myiptables-restore.service 
  systemd:
    name: myiptables-restore.service
    enabled: yes

        
#================================ Configure logs ===================================================    
    
- name: BASTION SERVER FOR LOGS | INSTALL PACKAGES
  yum:
    name: 
      - systemd-journal-gateway
      - setools-console
      - setroubleshoot-server
      - systemd-journal-gateway
    state: present
  
- name: BASTION SERVER FOR LOGS | ADD LOGS SERVER TO /etc/systemd/journal-upload.conf
  lineinfile: 
    path: /etc/systemd/journal-upload.conf
    line: URL=http://192.168.100.6:19532
    state: present

- name: BASTION SERVER FOR LOGS | CONFIG FIREWALLD FOR LOGS
  shell: firewall-cmd --permanent --zone=public --add-port=19532/tcp ; firewall-cmd --reload
  
- name: BASTION SERVER | START myiptables-restore.service 
  systemd:
    name: myiptables-restore.service
    state: started    
  
- name: BASTION SERVER FOR LOGS | CONFIGURE SELINUX FOR JOURNAL-REMOTE
  shell: semanage port -a -t dns_port_t -p tcp 19532    
  
- name: BASTION SERVER FOR LOGS | ENABLE AND START systemd-journal-upload.service 
  systemd:
    name: systemd-journal-upload.service
    enabled: yes
    state: started 
